//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CodeFirstFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceMapping
    {
        public int Id { get; set; }
        public string TermName { get; set; }
        public int Money { get; set; }
    }
}
